### PR TITLE
WIP Transaction height calculation improved

### PR DESCRIPTION
**Pull request by sergeylappo**
Removed int increment on each new block for each transaction.
**Tests passed as multiple-hd-accounts**

### CODE REVIEW

**Comment by Giszmo** [comment]
This PR works under the assumption that there is only one blockstore syncing at a time, with `blockChainHeight` being a global state. I myself did observe `daysBehind` to fluctuate in our module.

This is what Hearn wrote in a `TODO` in `Context`:

> // TODO: Auto-register the block chain object here, and then use it in the (newly deprecated) TransactionConfidence.getDepthInBlocks() method: the new version should take an AbstractBlockChain specifically.
> //       Also use the block chain object reference from the context in PeerGroup and remove the other constructors, as it's easy to forget to wire things up.

**Comment by sergeylappo** [comment]
@Giszmo, the worst thing about context that it's thread-dependent. 
And as I see it does not really managed as supposed to everywhere... Yes, thinked again. For different wallets it could be still different height... So would need to change this somehow.
Would like to discuss.

**Comment by Giszmo** [comment]
@sergeylappo still want to work on this PR?

**Comment by sergeylappo** [comment]
@giszmo, no😕

**Pull request closed without merging**
